{% set name = "ribopipe" %}
{% set version = "v0.1.5beta" %}
{% set sha256 = "5dd3744495b8ee72b706e632b6cb9e860a6c7434cdc5b4be4cb4b05ade1f5b67" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/j-berg/ribopipe.git
  git_tag: master

build:
  entry_points:
    - ribopipe = ribopipe:main
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  host:
    - fastqc ==0.11.7
    - fastx_toolkit ==0.0.14
    - htseq ==0.9.1
    - picard ==2.18.3
    - samtools ==1.7
    - hisat2 ==2.1.0
    - star ==2.6.1b
    - pandas ==0.22.0
    - numpy ==1.14.3
    - matplotlib ==2.2.0
    - scipy ==1.0.0
    - seaborn ==0.9.0
    - plastid ==0.4.8
    - bedtools ==2.27.1
    - py2bit
    - pyBigWig
    - pysam
    - deeptools >=3.0.0

  run:
    - python

test:
  imports:
    - ribopipe
  commands:
    ribopipe --help

about:
  home: https://github.com/j-berg/ribopipe
  license: GPL-3.0
  license_file: LICENSE
  summary: Build via 'conda-build --python 3 ./meta.yaml'
